export enum ERROR_TYPES {
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  REGISTRATION_PROBLEM = 'REGISTRATION_PROBLEM',
  LOGIN_PROBLEM = 'LOGIN_PROBLEM',
  OAUTH_LOGIN_FAILURE = 'OAUTH_LOGIN_FAILURE',
  NO_ACCESS_TOKEN = 'NO_ACCESS_TOKEN',
  INVALID_OR_EXPIRED_TOKEN = 'INVALID_OR_EXPIRED_TOKEN',

  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  USERNAME_ALREADY_EXISTS = 'USERNAME_ALREADY_EXISTS',

  TYPING_CONTENT_ALREADY_EXISTS = 'TYPING_CONTENT_ALREADY_EXISTS',
  TYPING_CONTENT_CATEGORY_ALREADY_EXISTS = 'TYPING_CONTENT_CATEGORY_ALREADY_EXISTS',
}
